1_two_sum: 1_two_sum.c
	gcc 1_two_sum.c -o 1_two_sum
	./1_two_sum
2_add_two_numbers: 2_add_two_numbers.c
	gcc 2_add_two_numbers.c -o 2_add_two_numbers
	./2_add_two_numbers
3_longest_substring_without_repeating_characters: 3_longest_substring_without_repeating_characters.c
	gcc 3_longest_substring_without_repeating_characters.c -o 3_longest_substring_without_repeating_characters
	./3_longest_substring_without_repeating_characters
4_median_of_two_sorted_arrays: 4_median_of_two_sorted_arrays.c
	gcc 4_median_of_two_sorted_arrays.c -o 4_median_of_two_sorted_arrays
	./4_median_of_two_sorted_arrays
5_longest_palindromic_substring: 5_longest_palindromic_substring.c
	gcc 5_longest_palindromic_substring.c -o 5_longest_palindromic_substring
	./5_longest_palindromic_substring
clean:
	-@rm 1_two_sum
	-@rm 2_add_two_numbers
	-@rm 3_longest_substring_without_repeating_characters
	-@rm 4_median_of_two_sorted_arrays
	-@rm 5_longest_palindromic_substring
