1_two_sum: 1_two_sum.c
	gcc 1_two_sum.c -o 1_two_sum
	./1_two_sum
2_add_two_numbers: 2_add_two_numbers.c
	gcc 2_add_two_numbers.c -o 2_add_two_numbers
	./2_add_two_numbers
3_longest_substring_without_repeating_characters: 3_longest_substring_without_repeating_characters.c
	gcc 3_longest_substring_without_repeating_characters.c -o 3_longest_substring_without_repeating_characters
	./3_longest_substring_without_repeating_characters
clean:
	-@rm 1_two_sum
	-@rm 2_add_two_numbers
	-@rm 3_longest_substring_without_repeating_characters
