1_two_sum: 1_two_sum.c
	gcc 1_two_sum.c -o 1_two_sum
	./1_two_sum
2_add_two_numbers: 2_add_two_numbers.c
	gcc 2_add_two_numbers.c -o 2_add_two_numbers
	./2_add_two_numbers
3_longest_substring_without_repeating_characters: 3_longest_substring_without_repeating_characters.c
	gcc 3_longest_substring_without_repeating_characters.c -o 3_longest_substring_without_repeating_characters
	./3_longest_substring_without_repeating_characters
4_median_of_two_sorted_arrays: 4_median_of_two_sorted_arrays.c
	gcc 4_median_of_two_sorted_arrays.c -o 4_median_of_two_sorted_arrays
	./4_median_of_two_sorted_arrays
5_longest_palindromic_substring: 5_longest_palindromic_substring.c
	gcc 5_longest_palindromic_substring.c -o 5_longest_palindromic_substring
	./5_longest_palindromic_substring
6_zigzag_conversion: 6_zigzag_conversion.c
	gcc 6_zigzag_conversion.c -o 6_zigzag_conversion
	./6_zigzag_conversion
7_reverse_integer: 7_reverse_integer.c
	gcc 7_reverse_integer.c -o 7_reverse_integer
	./7_reverse_integer
10_regular_expression_matching: 10_regular_expression_matching.c
	gcc 10_regular_expression_matching.c -o 10_regular_expression_matching
	./10_regular_expression_matching
clean:
	-@rm 1_two_sum
	-@rm 2_add_two_numbers
	-@rm 3_longest_substring_without_repeating_characters
	-@rm 4_median_of_two_sorted_arrays
	-@rm 5_longest_palindromic_substring
	-@rm 6_zigzag_conversion
	-@rm 7_reverse_integer
	-@rm 10_regular_expression_matching
